name: test
on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
      - name: test
        run: npm test
      - name: build
        run: npm run build
  deployment:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: upload
        run: echo "upload to server"